# Generated by Django 4.1 on 2022-09-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarephoto',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='softwarephoto',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
