# Generated by Django 4.1 on 2022-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_alter_softwarephoto_options_softwarephoto_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamephoto',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='gamephoto',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
