# Generated by Django 4.1 on 2022-09-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_rename_category_game_category_alter_game_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Category',
            new_name='Category',
        ),
    ]
