# Generated by Django 4.1 on 2022-09-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_rename_game_category_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Game_Category',
        ),
    ]
