# Generated by Django 4.1 on 2022-09-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_rename_category_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='game_category',
        ),
    ]
