# Generated by Django 4.1 on 2022-09-08 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_software_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='software_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.software_category', verbose_name='Kategorya'),
        ),
    ]
