# Generated by Django 4.1 on 2022-09-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_rename_slug_software_category_slug1'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='game_likes', to='software.ipmodel'),
        ),
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='game_views', to='software.ipmodel'),
        ),
    ]
