# Generated by Django 4.1 on 2022-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0012_ipmodel_game_likes_game_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='views',
        ),
        migrations.AddField(
            model_name='game',
            name='dislike_cont',
            field=models.PositiveIntegerField(default=0, verbose_name='dislike lar soni'),
        ),
        migrations.AddField(
            model_name='game',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='yuklashlar soni'),
        ),
        migrations.AddField(
            model_name='game',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='like lar soni'),
        ),
        migrations.AddField(
            model_name='game',
            name='seen_count',
            field=models.PositiveIntegerField(default=0, verbose_name="ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='software',
            name='dislike_cont',
            field=models.PositiveIntegerField(default=0, verbose_name='dislike lar soni'),
        ),
        migrations.AddField(
            model_name='software',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='yuklashlar soni'),
        ),
        migrations.AddField(
            model_name='software',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='like lar soni'),
        ),
        migrations.AddField(
            model_name='software',
            name='seen_count',
            field=models.PositiveIntegerField(default=0, verbose_name="ko'rishlar soni"),
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
