# Generated by Django 3.1.1 on 2022-09-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0014_auto_20220917_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism familya')),
                ('body', models.TextField(verbose_name='Izoh')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='software.software', verbose_name='Post')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
