# Generated by Django 3.1.1 on 2022-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0017_auto_20220920_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqti'),
        ),
    ]
