# Generated by Django 3.1.1 on 2022-09-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0018_auto_20220920_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software_category',
            old_name='slug1',
            new_name='slug',
        ),
    ]
